apiVersion: v1
kind: Service
metadata:
  name: tryingadventure-redis
  namespace: tryingadventure
spec:
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: redis
  selector:
    app.kubernetes.io/instance: tryingadventure-redis
    app.kubernetes.io/name: tryingadventure-redis
status:
  loadBalancer: {}
