stages:
  - test
  - build
  - deploy 
variables:
    ANSIBLE_HOST_KEY_CHECKING: 'false'
    ANSIBLE_FORCE_COLOR: 'true'
    ANSIBLE_PYTHON_INTERPRRTER: /usr/bin/python3
    CI_DEBUG_TRACE: "false"

test:
  script:
    - /usr/local/go/bin/go build -o goblog cmd/goblog/main.go
build: 
  script:
    - docker build .  --tag=artifact.tryingadventure.com/goblog:${CI_COMMIT_SHORT_SHA}
    - docker push artifact.tryingadventure.com/goblog:${CI_COMMIT_SHORT_SHA}

deploy:
  script:
    - cd deploy/tryingadventure/overlays/prod
    - kustomize edit set image artifact.tryingadventure.com/goblog=artifact.tryingadventure.com/goblog:${CI_COMMIT_SHORT_SHA}  
    - kubectl -n tryingadventure apply -k . 
