apiVersion: v1
kind: Service
metadata:
  name: tryingadventure-internal
  namespace: tryingadventure
  labels:
    app: tryingadventure-internal
spec:
  ports:
  - name: http-internal
    port: 5000
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: tryingadventure
    app.kubernetes.io/name: tryingadventure