apiVersion: v1
kind: Service
metadata:
  name: tryingadventure
  namespace: tryingadventure
  labels:
    app: tryingadventure
spec:
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 32020
    port: 5000
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: tryingadventure
    app.kubernetes.io/name: tryingadventure
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}