apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: tryingadventure-metrics-servicemonitor
    app.kubernetes.io/instance: tryingadventure
    release: prometheus
  name: tryingadventure-metrics-servicemonitor
  namespace: tryingadventure
spec:
  endpoints:
  - interval: 15s
    path: metrics
    port: http-internal
  selector:
    matchLabels:
      app: tryingadventure-internal