version: 2.1

orbs:
  #aws-ecr: circleci/aws-ecr@6.7.0
  aws-ecr: circleci/aws-ecr@6.15.3

workflows:
  ECRGoVipsWorkFlow:
    jobs:
      - build-ecr:
          context:
            - AWS
            - DockerHub
            - MaxMind
        
jobs:
  build-ecr:
    docker:
      - image: cimg/python:3.8.7
        auth:
          username: $username
          password: $password
       
    steps:
      - setup_remote_docker:
          version: 19.03.13

      - aws-ecr/ecr-login:
          account-url: goblog_url
          aws-access-key-id: circleci_key
          aws-secret-access-key: circleci_secret
          region: circleci_region

      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          ACCOUNT_ID=${ACCOUNT_ID} LICENSE_KEY=${LICENSE_KEY} docker build -t ${goblog_url}/blog:$TAG .

      - aws-ecr/push-image:
          account-url: goblog_url
          tag: "$CIRCLE_SHA1"
          repo: blog
