version: 2.1

workflows:
  ISSBuilder:
    jobs:
      - build-docker:
          context:
            - Artifactory
            - DockerHub
            - MaxMind
        
jobs:
  build-docker:
    docker:
      - image: circleci/golang:1.15
        auth:
          username: $username
          password: $password  # context / project UI env-var reference
    steps:
      - checkout
      # ... steps for building/testing app ...
      - setup_remote_docker:
          version: 20.10.7
      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          echo $registry_password | docker login artifact.tryingadventure.com --username $registry_user --password-stdin
          docker build --build-arg ACCOUNT_ID=${ACCOUNT_ID} --build-arg LICENSE_KEY=${LICENSE_KEY} -t artifact.tryingadventure.com/goblog:$TAG .
          docker push artifact.tryingadventure.com/goblog:$TAG

