version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.15.3

workflows:
  ECRGoBlogWorkFlow:
    jobs:
      - build-ecr:
          context:
            - AWS
            - DockerHub
            - MaxMind
        
jobs:
  build-dockerhub:
    docker:
      - image: circleci/golang:1.15
        auth:
          username: $username
          password: $password  # context / project UI env-var reference
    steps:
      - checkout
      # ... steps for building/testing app ...

      - setup_remote_docker:
          version: 19.03.13

      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t rsvancara/goblog:$TAG .
          echo "HEY THIS IS A VALUE ${DOCKER_HUB_USER}"
          echo $password | docker login --username $username --password-stdin
          docker push rsvancara/goblog:$TAG

  build-ecr:
    docker:
      - image: cimg/python:3.8.7
        auth:
          username: $username
          password: $password
       
    steps:
      - setup_remote_docker:
          version: 19.03.13

      - aws-ecr/build-and-push-image:
          account-url: goblog_url
          aws-access-key-id: circleci_key
          aws-secret-access-key: circleci_secret
          create-repo: true
          dockerfile: Dockerfile
          extra-build-args: "--build-arg ACCOUNT_ID=${ACCOUNT_ID} --build-arg LICENSE_KEY=${LICENSE_KEY}"
          path: .
          region: circleci_region
          repo: blog
          tag: "$CIRCLE_SHA1"

