apiVersion: v1
kind: Service
metadata:
  name: {{ include "diytinytrailer.fullname" . }}
  labels:
    {{- include "diytinytrailer.labels" . | nindent 4 }}
    k8s-app: {{ include "diytinytrailer.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "diytinytrailer.selectorLabels" . | nindent 4 }}
