apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "tryingadventure.fullname" . }}-metrics-servicemonitor
  # Change this to the namespace the Prometheus instance is running in
  namespace: default
  labels:
    app: {{ include "tryingadventure.fullname" . }}-metrics-servicemonitor
    release: prometheus
spec:
  selector:
    matchLabels:
      app: {{ include "tryingadventure.fullname" . }} # target gitlab service
  endpoints:
  - port: http
    interval: 15s
    path: "metrics"