apiVersion: apps/v1
kind: Deployment
metadata:
  name: tryingadventure # necessary for Kustomize identification
  namespace: tryingadventure
spec:
  replicas: 1 
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
