apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


commonLabels:
  env: tryingadventure

resources:
- namespace.yml
- ../../base

namespace: tryingadventure

patchesStrategicMerge:
- deployment.yml
images:
- name: artifact.tryingadventure.com/goblog
  newName: artifact.tryingadventure.com/goblog
  newTag: 4183798c 
